require('config.lsp')
require('config.options')
require('config.colorschemes')
require('config.snacks')
require('config.keymaps')
require('config.barbar')
require('config.resession')
require('config.mini')
